### ISSUE TITLE
Need new verb "Validate" in Update-ScriptFileInfo

### ISSUE THREAD

**Issue by MaxTrinidad** [anpur/powershellget-module#1]
Currently the cmdlet Update-ScriptFileInfo serves two purpose: to validate and update. We need a new "Validate" verb to separate the two purpose function in this particular cmdlet. 

Update-ScriptFileInfo
Syntax
    Update-ScriptFileInfo [-Path] <String> [-Version <Version>] [-Author <String>] [-Guid <Guid>] [-Description 

<String>] [-CompanyName <String>] [-Copyright <String>] [-RequiredModules <Object[]>] [-ExternalModuleDependencies 

<String[]>] [-RequiredScripts <String[]>] [-ExternalScriptDependencies <String[]>] [-Tags <String[]>] [-ProjectUri 

<Uri>] [-LicenseUri <Uri>] [-IconUri <Uri>] [-ReleaseNotes <String[]>] [-PassThru ] [-Force ] [-WhatIf ] [-Confirm ] 

[<CommonParameters>]

```
Update-ScriptFileInfo [-LiteralPath] <String> [-Version <Version>] [-Author <String>] [-Guid <Guid>] [-Description 
```

<String>] [-CompanyName <String>] [-Copyright <String>] [-RequiredModules <Object[]>] [-ExternalModuleDependencies 

<String[]>] [-RequiredScripts <String[]>] [-ExternalScriptDependencies <String[]>] [-Tags <String[]>] [-ProjectUri 

<Uri>] [-LicenseUri <Uri>] [-IconUri <Uri>] [-ReleaseNotes <String[]>] [-PassThru ] [-Force ] [-WhatIf ] [-Confirm ] 

[<CommonParameters>]

At the same time this new verb could apply to any existing and new cmdlets.

Existing cmdlet: Update-ScriptFileInfo 
New verb in cmdlet: Validate-ScriptFileInfo

**Comment by anpur** [comment]
Hi Max,

Sorry for confusion, but this repo is just an example of module to be published to PowerShell Gallery via PowerShellGet, not PowerShellGet itself.
I don't think that PowerShellGet is on GitHub, but you should try to raise ticket at OneGet (I see you already did).
