### ISSUE TITLE
Adding DLLs along with the Nuget package

### ISSUE THREAD

**Issue by pravchuk** [anpur/powershellget-module#4]
Hi Anpur, Lovely piece of code. This is really useful. 

I am creating a Powershell Module that needs a dll to be used. Any idea how I can add the dlls to the nuget?

**Comment by anpur** [comment]
Hi Praveen,

If you want to write entire PS module with C# you should check [How to Write a PowerShell Binary Module](https://technet.microsoft.com/en-us/library/dd878342.aspx).

If you just want to add a DLL to your script module I believe you can simply invoke DLL from your script as in [this article](http://www.leeholmes.com/blog/2006/10/27/load-a-custom-dll-from-powershell) and [add it to PS module manifest](https://msdn.microsoft.com/en-us/library/dd878337.aspx). 

Can't tell in more details as I don't have a Windows system now.

Also, for such questions you should create questions on StackOverflow, not issues on GitHub :D
